// comptab — shell completion generators.
// Emits bash, zsh, and fish completion scripts from a CommandNode tree.
// Deterministic, dependency-free, offline. Output is plain text you can pipe to
// a file or `eval`/`source`.

import type { CommandNode } from './model.js';
import type { CmdOption } from './parser.js';

export type Shell = 'bash' | 'zsh' | 'fish';

// ---- shared helpers --------------------------------------------------------

/** All long+short flag tokens for an option (already like "--all", "-a"). */
function flagTokens(o: CmdOption): string[] {
  return o.flags.filter((f) => /^-/.test(f));
}

function takesArg(o: CmdOption): boolean {
  return o.arg != null && o.arg !== '';
}

/** Collapse a description to a single short clean line fit for a completion menu. */
function oneLine(s: string): string {
  let d = (s || '').replace(/\s+/g, ' ').trim();
  // Man-page descriptions can be paragraphs; keep the first sentence and cap length.
  const stop = d.search(/\.\s/);
  if (stop !== -1 && stop < 80) d = d.slice(0, stop);
  if (d.length > 80) d = d.slice(0, 77).replace(/\s+\S*$/, '') + '…';
  return d.replace(/\.$/, '');
}

/** A safe identifier fragment for function names. */
function ident(s: string): string {
  return s.replace(/[^A-Za-z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'cmd';
}

function hasSubcommands(node: CommandNode): boolean {
  return node.subcommands.length > 0;
}

// ---- fish ------------------------------------------------------------------
// Fish has the cleanest model: one `complete` line per flag/subcommand, gated
// by `__fish_use_subcommand` / `__fish_seen_subcommand_from`.

function fishEscape(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function fishOptionLine(cmd: string, o: CmdOption, condition: string): string {
  const parts = [`complete -c ${cmd}`];
  if (condition) parts.push(condition);
  for (const f of flagTokens(o)) {
    if (/^--/.test(f)) parts.push(`-l ${f.slice(2)}`);
    else if (/^-/.test(f)) parts.push(`-s ${f.slice(1)}`);
  }
  if (takesArg(o)) parts.push('-r');
  const d = oneLine(o.description);
  if (d) parts.push(`-d '${fishEscape(d)}'`);
  return parts.join(' ');
}

export function generateFish(root: CommandNode): string {
  const cmd = root.name;
  const lines: string[] = [];
  lines.push(`# ${cmd} completions — generated by comptab from \`${cmd} --help\``);
  lines.push(`# https://github.com/esperanza-volkov/comptab`);
  lines.push('');

  const subNames = root.subcommands.map((s) => s.name);
  // Root flags stay available everywhere; subcommands only when none is chosen yet.
  const rootCond = subNames.length ? '-n __fish_use_subcommand' : '';

  // Root-level flags.
  for (const o of root.options) {
    lines.push(fishOptionLine(cmd, o, rootCond));
  }

  // Subcommands themselves.
  if (subNames.length) {
    lines.push('');
    for (const sub of root.subcommands) {
      const d = oneLine(sub.description);
      const dsc = d ? ` -d '${fishEscape(d)}'` : '';
      lines.push(`complete -c ${cmd} -f -n __fish_use_subcommand -a ${sub.name}${dsc}`);
    }
    // Per-subcommand flags.
    for (const sub of root.subcommands) {
      if (!sub.options.length) continue;
      lines.push('');
      lines.push(`# ${cmd} ${sub.name}`);
      const cond = `-n "__fish_seen_subcommand_from ${sub.name}"`;
      for (const o of sub.options) lines.push(fishOptionLine(cmd, o, cond));
    }
  }

  return lines.join('\n') + '\n';
}

// ---- zsh -------------------------------------------------------------------
// zsh is the richest: `_arguments` shows descriptions inline.

function zshEscape(s: string): string {
  // Inside single quotes; also neutralise the `[` `]` `:` that _arguments parses.
  return s.replace(/'/g, "'\\''").replace(/[\[\]:]/g, ' ').replace(/\s+/g, ' ').trim();
}

function zshArgSpec(o: CmdOption): string[] {
  const desc = zshEscape(oneLine(o.description));
  const arg = takesArg(o) ? ':' + zshEscape(o.arg!.replace(/[<>\[\]]/g, '')) + ':' : '';
  const toks = flagTokens(o);
  const specs: string[] = [];
  // Group short+long so zsh treats them as mutually exclusive aliases.
  const prefix = toks.length > 1 ? `(${toks.join(' ')})` : '';
  for (const f of toks) {
    specs.push(`'${prefix}${f}[${desc}]${arg}'`);
  }
  return specs;
}

export function generateZsh(root: CommandNode): string {
  const cmd = root.name;
  const fn = `_${ident(cmd)}`;
  const lines: string[] = [];
  lines.push(`#compdef ${cmd}`);
  lines.push(`# ${cmd} completions — generated by comptab from \`${cmd} --help\``);
  lines.push(`# https://github.com/esperanza-volkov/comptab`);
  lines.push('');

  if (!hasSubcommands(root)) {
    lines.push(`${fn}() {`);
    lines.push('  _arguments -s \\');
    const specs = root.options.flatMap(zshArgSpec);
    lines.push(specs.map((s) => '    ' + s).join(' \\\n'));
    lines.push('}');
    lines.push('');
    lines.push(`${fn} "$@"`);
    return lines.join('\n') + '\n';
  }

  // Subcommand-aware dispatcher.
  lines.push(`${fn}() {`);
  lines.push('  local curcontext="$curcontext" state line');
  lines.push('  _arguments -C \\');
  const rootSpecs = root.options.flatMap(zshArgSpec);
  for (const s of rootSpecs) lines.push('    ' + s + ' \\');
  lines.push("    '1: :->cmds' \\");
  lines.push("    '*::arg:->args'");
  lines.push('  case $state in');
  lines.push('    cmds)');
  lines.push('      local -a subcommands');
  lines.push('      subcommands=(');
  for (const sub of root.subcommands) {
    lines.push(`        '${sub.name}:${zshEscape(oneLine(sub.description))}'`);
  }
  lines.push('      )');
  lines.push(`      _describe -t commands '${cmd} command' subcommands`);
  lines.push('      ;;');
  lines.push('    args)');
  lines.push('      case $line[1] in');
  for (const sub of root.subcommands) {
    if (!sub.options.length) continue;
    lines.push(`        ${sub.name})`);
    lines.push('          _arguments -s \\');
    const specs = sub.options.flatMap(zshArgSpec);
    lines.push(specs.map((s) => '            ' + s).join(' \\\n'));
    lines.push('          ;;');
  }
  lines.push('      esac');
  lines.push('      ;;');
  lines.push('  esac');
  lines.push('}');
  lines.push('');
  lines.push(`${fn} "$@"`);
  return lines.join('\n') + '\n';
}

// ---- bash ------------------------------------------------------------------

function bashWords(root: CommandNode): { flags: string[]; subs: string[] } {
  const flags = new Set<string>();
  for (const o of root.options) for (const f of flagTokens(o)) flags.add(f);
  return { flags: [...flags], subs: root.subcommands.map((s) => s.name) };
}

export function generateBash(root: CommandNode): string {
  const cmd = root.name;
  const fn = `_${ident(cmd)}_comptab`;
  const { flags, subs } = bashWords(root);
  const lines: string[] = [];
  lines.push(`# ${cmd} completions — generated by comptab from \`${cmd} --help\``);
  lines.push(`# https://github.com/esperanza-volkov/comptab`);
  lines.push(`${fn}() {`);
  lines.push('  local cur prev words cword');
  lines.push('  _init_completion 2>/dev/null || { cur="${COMP_WORDS[COMP_CWORD]}"; prev="${COMP_WORDS[COMP_CWORD-1]}"; }');
  lines.push(`  local global_flags="${flags.join(' ')}"`);

  if (subs.length) {
    lines.push(`  local subcommands="${subs.join(' ')}"`);
    // find the chosen subcommand (first word after cmd that is a known sub)
    lines.push('  local i sub=""');
    lines.push('  for ((i=1; i < COMP_CWORD; i++)); do');
    lines.push('    case " $subcommands " in *" ${COMP_WORDS[i]} "*) sub="${COMP_WORDS[i]}"; break;; esac');
    lines.push('  done');
    lines.push('  case "$sub" in');
    for (const sub of root.subcommands) {
      const sf = new Set<string>();
      for (const o of sub.options) for (const f of flagTokens(o)) sf.add(f);
      lines.push(`    ${sub.name})`);
      lines.push(`      COMPREPLY=( $(compgen -W "${[...sf].join(' ')} $global_flags" -- "$cur") )`);
      lines.push('      return 0 ;;');
    }
    lines.push('    "")');
    lines.push('      if [[ "$cur" == -* ]]; then');
    lines.push('        COMPREPLY=( $(compgen -W "$global_flags" -- "$cur") )');
    lines.push('      else');
    lines.push('        COMPREPLY=( $(compgen -W "$subcommands" -- "$cur") )');
    lines.push('      fi');
    lines.push('      return 0 ;;');
    lines.push('  esac');
  } else {
    lines.push('  COMPREPLY=( $(compgen -W "$global_flags" -- "$cur") )');
    lines.push('  return 0');
  }
  lines.push('}');
  lines.push(`complete -F ${fn} ${cmd}`);
  return lines.join('\n') + '\n';
}

export function generate(root: CommandNode, shell: Shell): string {
  switch (shell) {
    case 'bash': return generateBash(root);
    case 'zsh': return generateZsh(root);
    case 'fish': return generateFish(root);
  }
}
